public class Day15 {

    public static void main(String[] args) {
        System.out.println("\t >>>OPERATOR ARITMATIKA<<<\n");
        int a = 26;
        int b = 4;
        double c = 1.1;

        //PENJUMLAHAN//
        double penjumlahan = a + b + c;
        int PENJUMLAHAN = a + b;

        //PENGURANGAN //
        double pengurangan = b - a - c;
        double Pengurangan = a - c;
        int PENGURANGAN = a - b;
        
        System.out.println(" \tPENJUMLAHAN\n");
        System.out.println(" HASIL =" + penjumlahan);
        System.out.println(" HASIL ="+ PENJUMLAHAN);
        
        System.out.println(" \tPENGURANGAN\n");
        System.out.println("HASIL ="+ pengurangan);
        System.out.println("HASIL ="+ Pengurangan);
        System.out.println("HASIL ="+ PENGURANGAN);
        
    }

}
