package daytwo;

public class DayTwo {

    public static void main(String[] args) {
     String nama = "nur alfiana";
     char JenisKelamin ='p';
     int tinggi = 158;
     double berat = 50.6;
     
        System.out.print("nama :" + nama);
        System.out.print("JenisKelamin :" + JenisKelamin);
        System.out.print("tinggi :" + tinggi);
        System.out.print("berat :" + berat);
        
        System.out.println("nama :" + nama);
        System.out.println("JenisKelamin :" +JenisKelamin);
        System.out.println("tinggi :" + tinggi);
        System.out.println("berat :" + berat);
        
        System.out.printf("\nnama:%s\nJenisKelamin:%c\ntinggi:%d: berat:%1f%n",nama,JenisKelamin,tinggi,berat);
        
     
     
     
   }
    
}
