package isc;

public class day26 {

    public static void main(String[] args) {
        System.out.println(" operator penugasan");
        int nilai = 123;
        nilai += 3;
        System.out.println(" hasil += :" + nilai);

        nilai -= 3;
        System.out.println(" hasil -= :" + nilai);

        nilai *= 2;
        System.out.println(" hasil *= :" + nilai);

        nilai /= 2;
        System.out.println(" hasil /= :" + nilai);

        nilai %= 12;
        System.out.println(" hasil %= :" + nilai);

    }
}
