
public class day4 {

    public static void main(String[] args) {
        System.out.printf("\t===BIODATA DIRI===\n");
        System.out.println(" Nama\t: NurAlfiana");
        System.out.println(" Umur\t: 18 Tahun");
        System.out.println(" Alamat\t : Sulawesi Barat");
        System.out.println(" Hobi\t : menggambar\r LULUS DDP YA ALLAH!!");
        System.out.println("\t==Terima Kasih!==");

        /*
        \n = untuk membuat pindah baris;
        \r = untuk menghilangkan kata yang ada di belakang r atau kata sebelum r
        \t = untuk tab atau membuat rapih jarak
         */
    }
}
