public class day5 {

    public static void main(String[] args) {
        System.out.printf("\n===Assalamualaikum===\n");
        byte umur = 18;
       short tahun = 2025;
       
       int jumlahPenduduk = 230000000;
       long jarakBumiKeMatahari = 149600000000L;
       
        System.out.println(" umur :" + umur);
        System.out.println(" tahun : " + tahun);
        System.out.println("jumlahPenduduk :" + jumlahPenduduk );
        System.out.println("jarakBumiKematahari :" + jarakBumiKeMatahari  + "KM");
        System.out.printf("\n ===TERIMA KASIH===");
        
    }
}
