package Piana;

public class nurAlfiana {
    public static void main(String[] args) {
        System.out.printf("\tASSALAMUALAIKUM!!\n");
        String N = "HALO MARONERSS!!";
        String R = "Selamat datang di Universitas Sulawesi barat";
        String L = "Silahkan memilih fakultas yang anda minati";
        String F = "setelah itu, silahkan memilih prodi";
        String P = "Selamat menjadi mahasiswa / mahasiswi Universitas Sulawesi barat";
        
        System.out.println(N);
        System.out.println(R);
        System.out.println(L);
        System.out.println(F);
        System.out.println(P);
        
        System.out.printf("\tTERIMA KASIH TELAH MELENGKAPI DATA ANDA!!");
   
    }
}
